#pragma once

    #define NUM_LOCK_INDICATOR_COLOR RGB_RED
    #define CAPS_LOCK_INDICATOR_COLOR RGB_RED
    #define SOLID_COLOR_RGB RGB_WHITE
    #define RGB_MATRIX_KEYPRESSES
    #define ENABLE_RGB_MATRIX_BACKLIT_SPLASH

    #define RGB_MATRIX_DEFAULT_SPD 20
    #define BACKLIT_SPLASH_WAVE_RGB 0xFF0000
    #define BACKLIT_SPLASH_WAVE_WIDTH 350